# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 58c3d9f43bab69fc08efe9cf00f85a8089422f776fbdcaf96b1263465316895a8f7e4e4fc7cdacf1288befe42ce40c118998a91d991c135dd7cb961aae392c92

test:
  secret_key_base: 6b0da28b022c8609d9444605fb8a203fa2f40d4daf6af43ecfb0b2d3fc79f8afd46cf4dee6fde88c86c3767631963f0d1f29215521e06176c1ade70196d7d1c3

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
